backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: config
    label: Site Configuration
    files:
      - name: config
        label: Site Configuration
        file: src/data/site-metadata.json
        fields:
          - widget: text
            name: description
            label: Description
            required: true
          - widget: image
            name: 'primaryLogo'
            label: 'Primary Logo'
            required: true
            hint: The main logo that gets displayed on the top of the page.
          - widget: image
            name: 'footerLogo'
            label: 'Footer Logo'
            required: true
            hint: The logo that will get displayed in the footer.
          - widget: image
            name: aboutImage
            label: About Homepage Image
            required: true
          - widget: string
            name: aboutTitle
            label: About Title
            required: true
          - label: 'Drop Date'
            name: 'dropDate'
            widget: 'date'
            default: ''
            format: 'MMM Do'

  - name: 'halfDeadBear'
    label: Half Dead Bear
    folder: 'src/data/bears'
    create: true
    fields:
      - { label: name, name: name, widget: string }
      - { label: Image, name: image, widget: image }
